name: Gemini Data Sync
on:
  workflow_dispatch:
  repository_dispatch:
    types: [update_data]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Update JSON
        run: |
          echo '${{ github.event.client_payload.data }}' > src/data/selected-pilot.json
          git config user.name "Gemini-AI"
          git config user.email "gemini@google.com"
          git add src/data/selected-pilot.json
          git commit -m "Auto-update property"
          git push
